HC_SB/Controllers/AdminUsuariosYRolesController.cs
using HC_SB.Authorize;
using HC_SB.EntidadesDominio.Autenticacion;
using HC_SB.Modelos.Autenticacion;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace HC_SB.Controllers
{
    public class AdminUsuariosYRolesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
      

        /// <summary>
        /// se muestra todos los usuarios del sistema
        /// </summary>
        /// <returns></returns>
        [HC_SBAuthorize(Roles = "Admin")]
        public ActionResult listaUsuarios()
        {

            var users = db.Users.ToList();
            List<EDUsuarioSistema> listaUsuarios = new List<EDUsuarioSistema>();
            foreach (var user in users)
            {

                var EDUsuarioSistema = new EDUsuarioSistema
                {
                    IDUser = user.Id,
                    userName = user.UserName,
                    nombreCompleto = user.nombreCompleto
                };
                listaUsuarios.Add(EDUsuarioSistema);

            }

            return View(listaUsuarios);
        }

        /// <summary>
        /// Metodo para eliminar un usuario del sistema
        /// </summary>
        /// <param name="idUser">id del usuario a borrar</param>
        /// <returns></returns>
        [HC_SBAuthorize(Roles = "Admin")]
        public ActionResult EliminarUsuario(string idUser)
        {

            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            var users = userManager.Users.ToList();
            var user = users.Find(u => u.Id == idUser);
            userManager.Delete(user);
            return RedirectToAction("listaUsuarios");

        }

        /// <summary>
        /// crear un nuevo rol
        /// </summary>
        /// <returns></returns>
        [HC_SBAuthorize(Roles = "Admin")]
        public ActionResult CrearRol()
        {            
            return View();
        }

        /// <summary>
        /// Crear un nuevo Rol
        /// </summary>
        /// <param name="Role"></param>
        /// <returns></returns>
        [HttpPost]
        [HC_SBAuthorize(Roles = "Admin")]
        public ActionResult CrearRol(IdentityRole Role)
        {
            db.Roles.Add(Role);
            db.SaveChanges();
            return RedirectToAction("listaRoles");
        }

        /// <summary>
        /// se muestra todos los roles del sistema
        /// </summary>
        /// <returns></returns>
        [HC_SBAuthorize(Roles = "Admin")]
        public ActionResult listaRoles()
        {

            var users = db.Roles.ToList();
            List<EDRol> listaRoles = new List<EDRol>();
            foreach (var user in users)
            {

                var EDRol = new EDRol
                {
                    IdRol = user.Id,
                    nombreRol = user.Name
                };
                listaRoles.Add(EDRol);

            }

            return View(listaRoles);
        }

        /// <summary>
        /// Metodo para listar todos los roles del usuario recibe como parametro el id del usuario
        /// </summary>
        /// <returns></returns>
        [HC_SBAuthorize(Roles = "Admin")]
        public ActionResult RolesPorUsuario(string id)
        {

            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            var rolMaager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(db));
            var user = userManager.Users.ToList().Find(u => u.Id == id);
            var roles = rolMaager.Roles.ToList();
            var rolesUser = new List<EDRol>();
            if (user.Roles != null)
            {

                foreach (var rol in user.Roles)
                {
                    var role = roles.Find(r => r.Id == rol.RoleId);
                    var EDRol = new EDRol
                    {
                        IdRol = role.Id,
                        nombreRol = role.Name

                    };
                    rolesUser.Add(EDRol);
                }

            }
            var EDUsuarioSistema = new EDUsuarioSistema
            {
                IDUser = user.Id,
                userName = user.UserName,
                nombreCompleto = user.nombreCompleto,
                roles = rolesUser

            };
            return View(EDUsuarioSistema);
        }

        /// <summary>
        /// Metodo para asignarle un rol a un usuario del sistema
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HC_SBAuthorize(Roles = "Admin")]
        public ActionResult AgregarRolUsuario(string id)
        {

            var user = db.Users.Find(id);
            var EDUsuarioSistema = new EDUsuarioSistema
            {
                IDUser = user.Id,
                userName = user.UserName,
                nombreCompleto = user.nombreCompleto,

            };
            ViewBag.rol = new SelectList(db.Roles, "id", "Name");
            return View(EDUsuarioSistema);
        }
        
        [HttpPost]
        [HC_SBAuthorize(Roles = "Admin")]
        public ActionResult AgregarRolUsuario(EDUsuarioSistema usuario)
        {

            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            var rolMaager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(db));

            var user = userManager.Users.ToList().Find(u => u.Id == usuario.IDUser);
            var rol = rolMaager.Roles.ToList().Find(r => r.Id == usuario.rol);
            if (!userManager.IsInRole(user.Id, rol.Name))
            {

                userManager.AddToRole(user.Id, rol.Name);
            }

            return RedirectToAction("listaUsuarios");

        }

        /// <summary>
        /// metodo para eliminar un rol al usuario 
        /// </summary>
        /// <param name="idUser"></param>
        /// <param name="idRol"></param>
        /// <returns></returns>
        [HC_SBAuthorize(Roles = "Admin")]
        public ActionResult EliminarRolUsuario(string idUser, string idRol)
        {

            if (string.IsNullOrEmpty(idUser) || string.IsNullOrEmpty(idRol))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            var rolMaager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(db));

            var user = userManager.Users.ToList().Find(u => u.Id == idUser);
            var rol = rolMaager.Roles.ToList().Find(r => r.Id == idRol);

         
            if (userManager.IsInRole(user.Id, rol.Name))
            {
                userManager.RemoveFromRole(user.Id, rol.Name);
            }

            /// retornando la vista para mostrar el usuario
            var Listaroles = rolMaager.Roles.ToList();
            var rolesUser = new List<EDRol>();
            if (user.Roles != null)
            {

                foreach (var rolUser in user.Roles)
                {
                    var role = Listaroles.Find(r => r.Id == rolUser.RoleId);
                    var EDRol = new EDRol
                    {
                        IdRol = role.Id,
                        nombreRol = role.Name

                    };
                    rolesUser.Add(EDRol);
                }

            }
            var EDUsuarioSistema = new EDUsuarioSistema
            {
                IDUser = user.Id,
                userName = user.UserName,
                nombreCompleto = user.nombreCompleto,
                roles = rolesUser
            };
            return View("RolesPorUsuario", EDUsuarioSistema);
        }

        /// <summary>
        /// Metodo para eliminar Roles
        /// </summary>
        /// <param name="idRol"></param>
        /// <param name="rolName"></param>
        /// <returns></returns>
        [HC_SBAuthorize(Roles = "Admin")]
        public ActionResult EliminarRol(string idRol, string rolName)
        {

            var rol = new IdentityRole();
            rol.Id = idRol;
            rol.Name = rolName;
            var rolMaager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(db));
            var roles = rolMaager.Roles.ToList();
            var rolDe = roles.Find(r => r.Id == rol.Id);
            rolMaager.Delete(rolDe);
            return RedirectToAction("listaRoles");
        }
    }
}

HC_SB/Controllers/TrabajoSocial/TrabajoSocialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HC_SB.Controllers.TrabajoSocial
{
    public class TrabajoSocialController : Controller
    {
        // GET: TrabajoSocial
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CrearVisita()
        {

            return View();
        }
    }
}

HC_SB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @using HC_SB.Modelos.Autenticacion;
    @using Microsoft.AspNet.Identity
    @using Microsoft.AspNet.Identity.EntityFramework;
    @if (Request.IsAuthenticated)
    {
        var manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
        var currentUser = manager.FindById(User.Identity.GetUserId());


        <div class="wrapper">
            <!-- Sidebar Holder -->
            <nav id="sidebar">
                <div class="sidebar-header">
                    <center><img src="~/Content/images/logo-sanbartolome.png" /></center>
                    <strong>Bienvenido @currentUser.nombreCompleto</strong>
                </div>

                <ul class="list-unstyled components">
                    <li class="active">
                        <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false">
                            <i class="glyphicon glyphicon-home"></i>
                            Historias Clínicas
                        </a>
                        <ul class="collapse list-unstyled" id="homeSubmenu">
                            <li>
                                <a href="#IdentificacionPaciente" data-toggle="collapse" aria-expanded="false">Identificación Paciente</a>
                                <ul class="collapse list-unstyled" id="IdentificacionPaciente">
                                    <li><a href="@Url.Action("CrearPaciente", "IdentificacionPaciente")">Buscar Paciente</a></li>
                                    <li><a href="@Url.Action("CrearPaciente", "IdentificacionPaciente")">Crear Paciente</a></li>
                                </ul>
                                <a href="#EntrevistaPsicologica" data-toggle="collapse" aria-expanded="false">Entrevista Inicial psicológica</a>
                                <ul class="collapse list-unstyled" id="EntrevistaPsicologica">
                                    <li><a href="@Url.Action("CrearPaciente", "IdentificacionPaciente")">Buscar Entrevista psicológica</a></li>
                                    <li><a href="@Url.Action("CrearPaciente", "IdentificacionPaciente")">Crear Entrevista psicológica</a></li>
                                </ul>
                                <a href="#EvaluaciónPsicologica" data-toggle="collapse" aria-expanded="false">Evaluación Inicial psicológica</a>
                                <ul class="collapse list-unstyled" id="EvaluaciónPsicologica">
                                    <li><a href="@Url.Action("CrearPaciente", "IdentificacionPaciente")">Buscar Evaluación psicológica</a></li>
                                    <li><a href="@Url.Action("CrearPaciente", "IdentificacionPaciente")">Crear Evaluación psicológica</a></li>
                                </ul>
                                <a href="#HojaDeTratamiento" data-toggle="collapse" aria-expanded="false">Hoja de tratamiento</a>
                                <ul class="collapse list-unstyled" id="HojaDeTratamiento">
                                    <li><a href="@Url.Action("CrearPaciente", "IdentificacionPaciente")">Buscar Hoja de tratamiento</a></li>
                                    <li><a href="@Url.Action("CrearPaciente", "IdentificacionPaciente")">Crear Hoja de tratamiento</a></li>
                                </ul>
                                <a href="#DiagnósticoFamiliar" data-toggle="collapse" aria-expanded="false">Diagnóstico Familiar</a>
                                <ul class="collapse list-unstyled" id="DiagnósticoFamiliar">
                                    <li><a href="@Url.Action("CrearPaciente", "IdentificacionPaciente")">Buscar Diagnóstico</a></li>
                                    <li><a href="@Url.Action("CrearPaciente", "IdentificacionPaciente")">Crear Diagnóstico</a></li>
                                </ul>
                                <a href="#Evaluación" data-toggle="collapse" aria-expanded="false">Evaluación</a>
                                <ul class="collapse list-unstyled" id="Evaluación">
                                    <li><a href="@Url.Action("CrearPaciente", "IdentificacionPaciente")">Buscar Evaluación</a></li>
                                    <li><a href="@Url.Action("CrearPaciente", "IdentificacionPaciente")">Crear Evaluación</a></li>
                                </ul>
                            </li>
                        </ul>

                    </li>
                    <li>
                        <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false">
                            <i class="glyphicon glyphicon-duplicate"></i>
                            Trabajo Social
                        </a>
                        <ul class="collapse list-unstyled" id="pageSubmenu">
                            <li><a href="#">Buscar Visita</a></li>
                            <li><a href="@Url.Action("CrearVisita", "TrabajoSocial")">Crear Visita</a></li>
                        </ul>
                    </li>
                    @if (User.IsInRole(System.Web.Configuration.WebConfigurationManager.AppSettings["Administrador"]))
                    {

                        <li>
                            <a href="#pageMaestros" data-toggle="collapse" aria-expanded="false">
                                <i class="glyphicon glyphicon-cog"></i>
                                Configuración de Maestros
                            </a>
                            <ul class="collapse list-unstyled" id="pageMaestros">
                                <li><a href="#">Maestro 1</a></li>
                                <li><a href="#")">Maestro 2</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#pageUsuariosSistema" data-toggle="collapse" aria-expanded="false">
                                <i class="glyphicon glyphicon-user"></i>
                                Usuarios y roles del Sistema
                            </a>
                            <ul class="collapse list-unstyled" id="pageUsuariosSistema">
                                <li><a href="@Url.Action("listaUsuarios", "AdminUsuariosYRoles")">Usuarios</a></li>
                                <li>@Html.ActionLink("Crear Usuario", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                                <li><a href="@Url.Action("listaRoles", "AdminUsuariosYRoles")">Roles</a></li>
                                <li><a href="@Url.Action("CrearRol", "AdminUsuariosYRoles")">Crear Rol</a></li>
                            </ul>
                        </li>
                    }
                    <li>
                        @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                        {
                            @Html.AntiForgeryToken()

                            <ul class="cerrarSesion">
                                <li><a href="javascript:document.getElementById('logoutForm').submit()">Cerrar sesión</a></li>
                            </ul>
                        }
                    </li>


                </ul>


            </nav>

            <!-- Page Content Holder -->
            <div id="content">

                <nav class="navbar navbar-default">
                    <div class="container-fluid">

                        <div class="navbar-header">
                            <button type="button" id="sidebarCollapse" class="btn btn-info navbar-btn">
                                <i class="glyphicon glyphicon-align-left"></i>
                                <span>Toggle Sidebar</span>
                            </button>
                        </div>


                    </div>
                </nav>

                <div class="container body-content">
                    @RenderBody()
                    <hr />
                    <footer>
                        <p>&copy; @DateTime.Now.Year - Historias Clínicas San Bartolome</p>
                    </footer>
                </div>
            </div>
        </div>
    }

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });
        });
    </script>

</body>
</html>